### ISSUE TITLE
Uncaught ReferenceError: Rails is not defined

### ISSUE THREAD

**Issue by 19940610mxh666** [farend/redmine_searchable_selectbox#12]
hi!
 thanks your plugins. 
but i get a mistake：Uncaught ReferenceError: Rails is not defined

Environment:
  Redmine version                3.4.5.stable.17297
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_searchable_selectbox   0.1.5

![微信截图_20210604155213](https://user-images.githubusercontent.com/26272545/120766999-5db18200-c54d-11eb-8c53-24de2d78eda1.png)

**Comment by ishikawa999** [comment]
@19940610mxh666 
Thank you for your feedback.

The notation Rails.fire is a function introduced from Rails 5.1, so it doesn't seem to work well with Redmine 3.4.
I think that it works for the time being by erasing the following two lines.
- https://github.com/farend/redmine_searchable_selectbox/blob/master/assets/javascripts/searchable_selectbox.js#L62
- https://github.com/farend/redmine_searchable_selectbox/blob/master/assets/javascripts/searchable_selectbox.js#L69

Most should work fine if you remove this line, but on rare occasions the problem is that the select box remains unsearchable. If you can't tolerate the problem, I recommend updating Redmine to 4.x.

**Comment by ishikawa999** [comment]
@19940610mxh666 

Updated the plugin so that you don't have to manually rewrite the code.　https://github.com/farend/redmine_searchable_selectbox/commit/763775ed429a3f36087eaaa6c5ebf87720e69508
If you `git clone` the latest plugin again, the error will disappear.

>Most should work fine if you remove this line, but on rare occasions the problem is that the select box remains unsearchable. If you can't tolerate the problem, I recommend updating Redmine to 4.x.

Even with the latest code, this probrem still exists.

**Comment by 19940610mxh666** [comment]
thank you!

**Comment by 19940610mxh666** [comment]
thank you!
